# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.host_name = "riemann.local"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.forward_port 4567, 4567
  config.vm.forward_port 5555, 5555
  config.vm.provision :shell, :path => "provision.sh"
end
